apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.configCLI.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
automountServiceAccountToken: false
